// GENERATED by scripts/build-group-course.js; edit group_course/lib instead.
"use strict";
const {
  MINUTE,
  C,
  ms,
  hash,
  random,
  BusinessError,
  fail,
  date,
  fee,
  campusCourts,
  occupied,
  deadlines,
  beijing,
  validatePublish,
  page,
} = require("./core");
function createService({
  repo,
  gateway,
  vip,
  clock = Date.now,
  logger = console,
}) {
  async function retry(fn) {
    for (let n = 0; n < 5; n++) {
      try {
        return await fn();
      } catch (e) {
        if (e.code !== "RETRYABLE_CONFLICT" || n === 4) throw e;
      }
    }
  }
  async function snapshot(id) {
    const c = await repo.get(C.course, id);
    if (!c) fail("COURSE_NOT_FOUND");
    const es = await repo.scan(C.enrollment, { courseId: id });
    return { c, es };
  }
  async function withCourse(id, fn) {
    return retry(async () => {
      const s = await snapshot(id);
      return repo.transaction(async (tx) => {
        const c = await tx.get(C.course, id);
        if (!c) fail("COURSE_NOT_FOUND");
        if (c.enrollmentVersion !== s.c.enrollmentVersion)
          fail("RETRYABLE_CONFLICT", true);
        return fn(tx, c, s.es);
      });
    });
  }
  async function bump(tx, c) {
    c.enrollmentVersion = (c.enrollmentVersion || 0) + 1;
    c.updatedAt = date(clock());
    await tx.set(C.course, c._id, c);
  }
  async function viewer(e, context) {
    // Same login contract as court_rush: reuse the app's phone identity.
    // Permission and VIP decisions are always queried on the server below.
    const phone = typeof e.phoneNumber === "string" ? e.phoneNumber.trim() : "";
    if (!phone)
      return {
        authenticated: false,
        phoneNumber: null,
        isAdmin: false,
        isVip: false,
      };
    const managers = await repo.scan("manager", { phoneNumber: phone });
    let isVip = null;
    // Only price reads and enrollment need membership; administration/refunds must not depend on it.
    if (["list", "detail", "enroll"].includes(e.action)) {
      try {
        isVip = await vip(phone);
      } catch (err) {
        logger.error("VIP lookup failed", err.code || err.message);
        fail("VIP_UNAVAILABLE", true);
      }
    }
    return {
      authenticated: true,
      phoneNumber: phone,
      isAdmin: managers.some(
        (m) => Number(m.courtRushManager) >= 1 || Number(m.specialManager) >= 1,
      ),
      isVip,
    };
  }
  const publicViewer = (v) => ({
    authenticated: v.authenticated,
    phoneNumber: v.phoneNumber,
    isAdmin: v.isAdmin,
    isVip: v.isVip,
  });
  const requireUser = (v) => {
    if (!v.authenticated) fail("AUTH_REQUIRED");
  };
  const requireAdmin = (v) => {
    requireUser(v);
    if (!v.isAdmin) fail("FORBIDDEN");
  };
  async function enrollmentDTO(e, c) {
    if (!e) return null;
    const r = e.refundId ? await repo.get(C.refund, e.refundId) : null;
    return {
      id: e._id,
      courseId: e.courseId,
      status: e.status,
      isVip: e.isVip,
      originalPriceYuan: e.originalPriceYuan,
      actualFeeYuan: e.actualFeeYuan,
      attemptStartedAt: ms(e.attemptStartedAt),
      holdExpiresAt: ms(e.attemptStartedAt) + 3 * MINUTE,
      paidAt: ms(e.paidAt),
      canCancel: e.status === "PAID" && clock() < deadlines(c).cancelDeadlineAt,
      refund: r
        ? { id: r._id, status: r.status, amountYuan: r.amountYuan }
        : null,
    };
  }
  function courseDTO(c, es, v) {
    const now = clock(),
      d = deadlines(c),
      count = es.filter((e) => occupied(e, now)).length;
    let reason = null;
    if (!v.authenticated) reason = "AUTH_REQUIRED";
    else if (c.status !== "PUBLISHED") reason = "ENROLLMENT_CLOSED";
    else if (now >= d.enrollmentDeadlineAt) reason = "ENROLLMENT_CLOSED";
    else if (
      es.some((e) => e.phoneNumber === v.phoneNumber && occupied(e, now))
    )
      reason = "ALREADY_ENROLLED";
    else if (count >= c.maxParticipants) reason = "COURSE_FULL";
    const result = {};
    for (const k of [
      "status",
      "templateId",
      "title",
      "description",
      "coachId",
      "coachName",
      "coachIntroduction",
      "campus",
      "courtId",
      "courtNumber",
      "bookingManaged",
      "minParticipants",
      "maxParticipants",
      "priceYuan",
      "vipPriceYuan",
    ])
      result[k] = c[k];
    return {
      ...result,
      id: c._id,
      startAt: ms(c.startAt),
      endAt: ms(c.endAt),
      publishedAt: ms(c.publishedAt),
      ...d,
      isVip: v.isVip,
      actualFeeYuan: fee(c.priceYuan, v.isVip, c.vipPriceYuan),
      paidCount: es.filter((e) => e.status === "PAID").length,
      occupiedCount: count,
      remainingSeats: Math.max(0, c.maxParticipants - count),
      canEnroll: !reason,
      enrollDisabledReason: reason,
    };
  }
  async function paymentDTO(e) {
    if (!e || e.status !== "PENDING_PAYMENT") return null;
    const course = await repo.get(C.course, e.courseId);
    if (!course || course.status === "CANCELLED") return null;
    const p = await repo.get(C.payment, e.paymentId);
    if (!p || p.status !== "PENDING" || clock() >= ms(p.createdAt) + 2 * MINUTE)
      return null;
    const q = p.paymentParams;
    if (
      !q ||
      !["timeStamp", "nonceStr", "package", "signType", "paySign"].every(
        (k) => typeof q[k] === "string" && q[k],
      )
    )
      return null;
    return {
      id: p._id,
      paymentParams: Object.fromEntries(
        ["timeStamp", "nonceStr", "package", "signType", "paySign"].map((k) => [
          k,
          q[k],
        ]),
      ),
      expiresAt: ms(p.createdAt) + 2 * MINUTE,
    };
  }
  // Teaching candidates reuse manager.name/phoneNumber; no separate coach collection or flag.
  const selectableCoach = (person) => !!person &&
    typeof person.name === "string" && !!person.name.trim() &&
    typeof person.phoneNumber === "string" && !!person.phoneNumber.trim();
  async function contextAction(e, v) {
    const campusRows = (await repo.scan("campus", { enabled: true }))
      .sort((a, b) => (a.sortOrder || 0) - (b.sortOrder || 0));
    const campuses = campusRows.map((x) => ({
        id: x._id,
        name: x.name,
        bookingManaged: !!x.bookingManaged,
        sortOrder: x.sortOrder || 0,
      }));
    const result = {
      viewer: publicViewer(v),
      campuses,
      courts: [],
      coaches: [],
      templates: [],
    };
    if (v.isAdmin) {
      const [courts, coaches, templates] = await Promise.all([
        repo.scan("court"),
        repo.scan("manager"),
        repo.scan("group_course_template", { enabled: true }),
      ]);
      result.courts = campusRows
        .flatMap((campus) => campusCourts(campus, courts))
        .map((x) => ({
          id: x._id,
          campus: x.campus,
          courtNumber: String(x.courtNumber),
        }));
      result.coaches = coaches.filter(selectableCoach).map((x) => ({
        id: x._id,
        name: x.name.trim(),
        introduction: "",
      }));
      result.templates = templates
        .sort((a, b) => (a.sortOrder || 0) - (b.sortOrder || 0))
        .map((x) => ({
          id: x._id,
          title: x.title,
          description: x.description,
        }));
    }
    return result;
  }
  async function list(e, v) {
    if (!["public", "mine"].includes(e.scope)) fail("INVALID_ARGUMENT");
    if (e.scope === "mine") requireUser(v);
    let rows;
    if (e.scope === "mine") {
      rows = await repo.scan(C.enrollment, { phoneNumber: v.phoneNumber });
      const pairs = await Promise.all(
        rows.map(async (x) => ({
          enrollment: x,
          course: await repo.get(C.course, x.courseId),
        })),
      );
      rows = pairs
        .filter((x) => x.course && (!e.campus || x.course.campus === e.campus))
        .map((x) => ({ ...x.enrollment, _course: x.course }));
    } else
      rows = (await repo.scan(C.course)).filter(
        (c) =>
          (v.isAdmin || c.status !== "CANCELLED") &&
          (!e.campus || c.campus === e.campus),
      );
    const p = page(
      rows,
      e.cursor,
      e.pageSize,
      e.scope === "mine" ? "createdAt" : "startAt",
      e.scope === "mine",
    );
    const items = [];
    for (const row of p.items) {
      const c = row._course || row;
      await settleCourse(c._id);
      await expireCourseHolds(c._id);
      const s = await snapshot(c._id);
      if (e.scope === "public" && !v.isAdmin && s.c.status === "CANCELLED")
        continue;
      const own = v.authenticated
        ? s.es.find((x) => x.phoneNumber === v.phoneNumber)
        : null;
      items.push({
        course: courseDTO(s.c, s.es, v),
        myEnrollment: await enrollmentDTO(own, s.c),
      });
    }
    return { viewer: publicViewer(v), items, nextCursor: p.nextCursor };
  }
  async function detail(e, v) {
    await settleCourse(e.courseId);
    await expireCourseHolds(e.courseId);
    const { c, es } = await snapshot(e.courseId);
    const own = v.authenticated
      ? es.find((x) => x.phoneNumber === v.phoneNumber)
      : null;
    if (c.status === "CANCELLED" && !v.isAdmin && !own)
      fail("COURSE_NOT_FOUND");
    const result = {
      viewer: publicViewer(v),
      course: courseDTO(c, es, v),
      myEnrollment: await enrollmentDTO(own, c),
      payment: await paymentDTO(own),
    };
    if (v.isAdmin) {
      const p = page(
        es,
        e.participantCursor,
        e.participantPageSize,
        "createdAt",
      );
      const refunds = await repo.scan(C.refund, { courseId: c._id });
      result.participants = p.items.map((x) => ({
        id: x._id,
        phoneNumber: x.phoneNumber,
        nickName: x.nickName || "",
        avatarUrl: x.avatarUrl || "",
        status: x.status,
        actualFeeYuan: x.actualFeeYuan,
        paidAt: ms(x.paidAt),
        refundStatus: refunds.find((r) => r._id === x.refundId)?.status || null,
      }));
      result.participantNextCursor = p.nextCursor;
      result.refundSummary = {
        pending: 0,
        processing: 0,
        success: 0,
        failed: 0,
      };
      for (const r of refunds) result.refundSummary[r.status.toLowerCase()]++;
    }
    return result;
  }
  async function publish(e, v) {
    requireAdmin(v);
    const p = validatePublish(e, clock());
    const id = hash(v.phoneNumber, e.publishRequestId),
      payloadHash = hash(p);
    return retry(async () => {
      const old = await repo.get(C.course, id);
      if (old) {
        if (old.publishPayloadHash !== payloadHash) fail("REQUEST_ID_CONFLICT");
        return { courseId: id, status: old.status, replayed: true };
      }
      if (clock() >= p.startAt - 60 * MINUTE) fail("PUBLISH_TOO_LATE");
      const [template, coach, campusRows, courts, otherCourses] =
        await Promise.all([
          repo.get("group_course_template", p.templateId),
          repo.get("manager", p.coachId),
          repo.scan("campus", { name: p.campus }),
          repo.scan("court", { campus: p.campus }),
          repo.scan(C.course),
        ]);
      if (!template || template.enabled !== true) fail("TEMPLATE_UNAVAILABLE");
      if (!selectableCoach(coach)) fail("COACH_UNAVAILABLE");
      const campus = campusRows.find((x) => x.enabled === true);
      if (!campus) fail("CAMPUS_UNAVAILABLE");
      const court = campusCourts(campus, courts).find((x) => x._id === p.courtId);
      if (!court || court.campus !== p.campus || court.courtNumber == null)
        fail("COURT_UNAVAILABLE");
      const overlapping = otherCourses.filter(
        (c) =>
          c.status !== "CANCELLED" &&
          ms(c.startAt) < p.endAt &&
          ms(c.endAt) > p.startAt,
      );
      if (overlapping.some((c) => c.coachId === p.coachId))
        fail("COACH_CONFLICT");
      if (
        overlapping.some(
          (c) =>
            c.campus === p.campus &&
            String(c.courtNumber) === String(court.courtNumber),
        )
      )
        fail("COURT_CONFLICT", false, { conflictCourtIds: [] });
      const slots = [];
      if (campus.bookingManaged) {
        for (let t = p.startAt; t < p.endAt; t += 30 * MINUTE) {
          const b = beijing(t);
          const court_id =
            String(court.courtNumber) + "_" + b.day + "_" + b.time;
          const found = await repo.scan(C.slot, { campus: p.campus, court_id });
          if (found.length > 1) fail("CONFIG_ERROR");
          slots.push({
            court_id,
            campus: p.campus,
            courtNumber: String(court.courtNumber),
            date: b.day,
            start_time: b.time,
            end_time: beijing(t + 30 * MINUTE).time,
            _existing: found[0]?._id,
          });
        }
      }
      return repo.transaction(async (tx) => {
        const replay = await tx.get(C.course, id);
        if (replay) {
          if (replay.publishPayloadHash !== payloadHash)
            fail("REQUEST_ID_CONFLICT");
          return { courseId: id, status: replay.status, replayed: true };
        }
        const now = clock();
        if (now >= p.startAt - 60 * MINUTE) fail("PUBLISH_TOO_LATE");
        for (const slot of slots) {
          const slotId = slot._existing || hash(slot.campus, slot.court_id);
          const existing = await tx.get(C.slot, slotId);
          if (existing && existing.status !== "free")
            fail("COURT_CONFLICT", false, {
              conflictCourtIds: [slot.court_id],
            });
          const { _existing, ...base } = slot;
          await tx.set(C.slot, slotId, {
            ...base,
            status: "booked",
            version: (existing?.version || 0) + 1,
            created_at: existing?.created_at || date(now),
            updated_at: date(now),
            deleted_at: null,
            price: null,
            is_verified: false,
            source_type: "GROUP_COURSE",
            group_course_id: id,
            booked_by: v.phoneNumber,
          });
        }
        await tx.set(C.course, id, {
          ...p,
          _id: id,
          status: "PUBLISHED",
          cancellationCleanupCompleted: false,
          maintenanceAt: null,
          coachName: coach.name.trim(),
          coachIntroduction: "",
          courtNumber: String(court.courtNumber),
          bookingManaged: !!campus.bookingManaged,
          courtIds: slots.map((x) => x.court_id),
          startAt: date(p.startAt),
          endAt: date(p.endAt),
          enrollmentVersion: 0,
          publishRequestId: e.publishRequestId,
          publishPayloadHash: payloadHash,
          createdBy: v.phoneNumber,
          publishedBy: v.phoneNumber,
          cancelledBy: "",
          createdAt: date(now),
          updatedAt: date(now),
          publishedAt: date(now),
          cancelledAt: null,
          cancelReason: "",
        });
        return { courseId: id, status: "PUBLISHED", replayed: false };
      });
    });
  }
  async function refundInTx(tx, c, e, p, reason) {
    const id = hash("refund", p._id);
    let r = await tx.get(C.refund, id);
    if (!r) {
      const now = date(clock());
      r = {
        _id: id,
        courseId: c._id,
        enrollmentId: e._id,
        paymentId: p._id,
        outRefundNo: hash("merchantRefund", p._id),
        wxRefundId: "",
        amountYuan: p.amountYuan,
        reason,
        status: "PENDING",
        nextAction: "SUBMIT",
        retryCount: 0,
        nextRetryAt: now,
        leaseToken: "",
        leaseUntil: null,
        lastAttemptAt: null,
        channelStatus: "",
        failureCode: "",
        failureMessage: "",
        createdAt: now,
        updatedAt: now,
        succeededAt: null,
      };
      await tx.set(C.refund, id, r);
    }
    if (e.paymentId === p._id) {
      e.refundId = id;
      e.status =
        r.status === "SUCCESS"
          ? "CANCELLED"
          : r.status === "FAILED" && r.nextRetryAt === null
            ? "REFUND_FAILED"
            : "REFUNDING";
      e.updatedAt = date(clock());
      await tx.set(C.enrollment, e._id, e);
    }
    return r;
  }
  async function settleCourse(id) {
    return withCourse(id, async (tx, c, es) => {
      const now = clock();
      if (c.status === "PUBLISHED" && now >= deadlines(c).formationAt) {
        const paid = es.filter(
          (e) =>
            e.status === "PAID" &&
            e.paidAt &&
            ms(e.paidAt) <= deadlines(c).formationAt,
        ).length;
        if (paid >= c.minParticipants) c.status = "CONFIRMED";
        else {
          c.status = "CANCELLED";
          c.cancelReason = "MIN_PARTICIPANTS_NOT_MET";
          c.cancelledAt = date(now);
        }
        await bump(tx, c);
      }
      if (c.status === "CONFIRMED" && now >= ms(c.endAt)) {
        c.status = "COMPLETED";
        await bump(tx, c);
      }
      return c;
    });
  }
  async function expireCourseHolds(id) {
    let processed;
    do {
      processed = await withCourse(id, async (tx, c, es) => {
        let changed = 0;
        for (const e of es) {
          // Each enrollment writes two documents; keep transactions bounded.
          if (changed >= 20) break;
          if (
            e.status !== "PENDING_PAYMENT" ||
            (c.status !== "CANCELLED" &&
              ms(e.attemptStartedAt) + 3 * MINUTE > clock())
          )
            continue;
          const live = await tx.get(C.enrollment, e._id);
          if (
            !live ||
            live.status !== "PENDING_PAYMENT" ||
            live.paymentId !== e.paymentId
          )
            fail("RETRYABLE_CONFLICT", true);
          const p = await tx.get(C.payment, e.paymentId);
          live.status = "EXPIRED";
          live.updatedAt = date(clock());
          await tx.set(C.enrollment, e._id, live);
          if (p && p.status === "PENDING" && c.status !== "CANCELLED") {
            p.status = "EXPIRED";
            p.updatedAt = date(clock());
            await tx.set(C.payment, p._id, p);
          }
          changed += 1;
        }
        if (changed) await bump(tx, c);
        return changed;
      });
    } while (processed === 20);
  }
  async function enroll(e, v, context) {
    requireUser(v);
    await settleCourse(e.courseId);
    await expireCourseHolds(e.courseId);
    const result = await withCourse(e.courseId, async (tx, c, es) => {
      const now = clock(),
        id = hash(c._id, v.phoneNumber);
      const existing = await tx.get(C.enrollment, id);
      if (c.status === "CANCELLED") fail("ENROLLMENT_CLOSED");
      if (
        existing?.status === "PENDING_PAYMENT" &&
        ms(existing.attemptStartedAt) + 3 * MINUTE > now
      )
        return { e: existing, c, created: false };
      if (
        existing &&
        ["PAID", "REFUNDING", "REFUND_FAILED"].includes(existing.status)
      )
        fail("ALREADY_ENROLLED");
      if (c.status !== "PUBLISHED" || now >= deadlines(c).enrollmentDeadlineAt)
        fail("ENROLLMENT_CLOSED");
      if (es.filter((x) => occupied(x, now)).length >= c.maxParticipants)
        fail("COURSE_FULL");
      const paymentId = random();
      const enrollment = {
        _id: id,
        courseId: c._id,
        phoneNumber: v.phoneNumber,
        nickName:
          typeof e.nickName === "string" ? e.nickName.slice(0, 100) : "",
        avatarUrl:
          typeof e.avatarUrl === "string" ? e.avatarUrl.slice(0, 2000) : "",
        status: "PENDING_PAYMENT",
        isVip: v.isVip,
        originalPriceYuan: c.priceYuan,
        actualFeeYuan: fee(c.priceYuan, v.isVip, c.vipPriceYuan),
        attemptStartedAt: date(now),
        paymentId,
        refundId: "",
        paidAt: null,
        cancelledAt: null,
        createdAt: existing?.createdAt || date(now),
        updatedAt: date(now),
      };
      const payment = {
        _id: paymentId,
        courseId: c._id,
        enrollmentId: id,
        phoneNumber: v.phoneNumber,
        outTradeNo: random(),
        wxTransactionId: "",
        amountYuan: enrollment.actualFeeYuan,
        status: "PENDING",
        paymentParams: null,
        queryNextAt: null,
        createdAt: date(now),
        updatedAt: date(now),
        paidAt: null,
        notifyAt: null,
        failureCode: "",
        failureMessage: "",
      };
      await tx.set(C.enrollment, id, enrollment);
      await tx.set(C.payment, paymentId, payment);
      await bump(tx, c);
      return { e: enrollment, p: payment, c, created: true };
    });
    if (result.created) {
      let response;
      try {
        response = await gateway.createPayment(
          result.p,
          result.c,
          // Payment transport only; business identity and permissions use phoneNumber.
          context.OPENID,
        );
      } catch (err) {
        logger.error("create payment unresolved", {
          paymentId: result.p._id,
          error: err.code || err.message,
        });
        response = { state: "UNKNOWN" };
      }
      if (response.state === "CREATED") {
        await repo.transaction(async (tx) => {
          const p = await tx.get(C.payment, result.p._id);
          if (p.status === "PENDING") {
            p.paymentParams = response.paymentParams;
            p.updatedAt = date(clock());
            await tx.set(C.payment, p._id, p);
          }
        });
      } else if (response.state === "FAILED") {
        await withCourse(e.courseId, async (tx, c) => {
          const p = await tx.get(C.payment, result.p._id),
            en = await tx.get(C.enrollment, result.e._id);
          if (p.status !== "PENDING") return;
          p.status = "FAILED";
          p.failureCode = response.code || "CREATE_FAILED";
          p.updatedAt = date(clock());
          await tx.set(C.payment, p._id, p);
          if (en.paymentId === p._id && en.status === "PENDING_PAYMENT") {
            en.status = "EXPIRED";
            en.updatedAt = date(clock());
            await tx.set(C.enrollment, en._id, en);
            await bump(tx, c);
          }
        });
        fail("PAYMENT_UNAVAILABLE", true);
      }
    }
    const en = await repo.get(C.enrollment, result.e._id);
    return {
      courseId: e.courseId,
      enrollment: await enrollmentDTO(en, result.c),
      payment: await paymentDTO(en),
    };
  }
  async function confirmPayment(id, result) {
    const original = await repo.get(C.payment, id);
    if (!original) return;
    return withCourse(original.courseId, async (tx, c) => {
      const p = await tx.get(C.payment, id);
      if (p.status === "PAIDED") return;
      if (p.status !== "PENDING") {
        logger.warn("late payment outside accepted scope", {
          paymentId: id,
          status: p.status,
        });
        return;
      }
      const e = await tx.get(C.enrollment, p.enrollmentId);
      if (result.state !== "PAID") {
        // Cancellation closes the client entry immediately, but retains the
        // merchant payment until a query establishes that it was not paid.
        if (
          c.status === "CANCELLED" &&
          (result.state === "CLOSED" ||
            (result.state === "UNPAID" &&
              clock() >= ms(p.createdAt) + 3 * MINUTE))
        ) {
          p.status = "EXPIRED";
          p.updatedAt = date(clock());
          await tx.set(C.payment, p._id, p);
        }
        return;
      }
      const cancelledPending =
        c.status === "CANCELLED" && e?.status === "EXPIRED";
      if (
        !e ||
        e.paymentId !== p._id ||
        (e.status !== "PENDING_PAYMENT" && !cancelledPending)
      ) {
        logger.warn("payment no longer current", { paymentId: id });
        return;
      }
      const now = date(clock());
      p.status = "PAIDED";
      p.wxTransactionId = result.transactionId;
      p.paidAt = now;
      p.notifyAt = now;
      p.updatedAt = now;
      e.status = "PAID";
      e.paidAt = now;
      e.updatedAt = now;
      await tx.set(C.payment, id, p);
      await tx.set(C.enrollment, e._id, e);
      if (c.status === "CANCELLED")
        await refundInTx(tx, c, e, p, c.cancelReason || "COURSE_CANCELLED");
      await bump(tx, c);
    });
  }
  async function paymentCallback(event) {
    try {
      const no = event.outTradeNo || event.out_trade_no;
      if (!no) return { errcode: 0, errmsg: "OK" };
      const p = (await repo.scan(C.payment, { outTradeNo: no }))[0];
      if (!p) {
        logger.warn("unknown payment callback");
        return { errcode: 0, errmsg: "OK" };
      }
      if (p.status === "PAIDED") return { errcode: 0, errmsg: "OK" };
      const result = await gateway.queryPayment(p);
      if (result.state === "UNKNOWN") throw Error("PAYMENT_QUERY_UNRESOLVED");
      await confirmPayment(p._id, result);
      return { errcode: 0, errmsg: "OK" };
    } catch (err) {
      logger.error("payment callback retry", err.code || err.message);
      return { errcode: 1, errmsg: "RETRY" };
    }
  }
  async function cancelEnrollment(e, v) {
    requireUser(v);
    await withCourse(e.courseId, async (tx, c) => {
      const en = await tx.get(C.enrollment, hash(c._id, v.phoneNumber));
      if (!en) fail("ENROLLMENT_NOT_FOUND");
      if (["REFUNDING", "REFUND_FAILED", "CANCELLED"].includes(en.status))
        return;
      if (en.status !== "PAID") fail("ENROLLMENT_NOT_FOUND");
      if (clock() >= deadlines(c).cancelDeadlineAt)
        fail("CANCEL_WINDOW_CLOSED");
      const p = await tx.get(C.payment, en.paymentId);
      if (!p || p.status !== "PAIDED") fail("PAYMENT_PENDING", true);
      await refundInTx(tx, c, en, p, "USER_CANCELLED");
      await bump(tx, c);
    });
    const s = await snapshot(e.courseId);
    return {
      courseId: e.courseId,
      enrollment: await enrollmentDTO(
        s.es.find((x) => x.phoneNumber === v.phoneNumber),
        s.c,
      ),
    };
  }
  async function repairCancelled(id) {
    const c = await repo.get(C.course, id);
    if (!c || c.status !== "CANCELLED") return;
    const slots = await repo.scan(C.slot, {
      source_type: "GROUP_COURSE",
      group_course_id: id,
    });
    for (const slot of slots)
      await isolate(
        async () =>
          repo.transaction(async (tx) => {
            const s = await tx.get(C.slot, slot._id);
            if (
              !s ||
              s.source_type !== "GROUP_COURSE" ||
              s.group_course_id !== id
            )
              return;
            const clean = {};
            for (const k of [
              "court_id",
              "campus",
              "courtNumber",
              "date",
              "start_time",
              "end_time",
              "created_at",
            ])
              clean[k] = s[k];
            await tx.set(C.slot, s._id, {
              ...clean,
              status: "free",
              version: (s.version || 0) + 1,
              updated_at: date(clock()),
              deleted_at: null,
              price: null,
              is_verified: false,
            });
          }),
        "release slot",
      );
    const payments = await repo.scan(C.payment, { courseId: id });
    const refunds = await repo.scan(C.refund, { courseId: id });
    const missing = payments.filter(
      (p) =>
        p.status === "PAIDED" && !refunds.some((r) => r.paymentId === p._id),
    );
    // Persist one task per payment. Completed and paused refunds are never reset.
    for (const p of missing.slice(0, 50))
      await isolate(async () => {
        await withCourse(id, async (tx, current) => {
          const pay = await tx.get(C.payment, p._id);
          const en = await tx.get(C.enrollment, p.enrollmentId);
          if (pay?.status === "PAIDED" && en) {
            await refundInTx(
              tx,
              current,
              en,
              pay,
              current.cancelReason || "COURSE_CANCELLED",
            );
            await bump(tx, current);
          }
        });
      }, "cancel refund repair");
    await expireCourseHolds(id);
    if (
      !payments.some((p) => p.status === "PENDING") &&
      missing.length === 0 &&
      slots.length === 0
    ) {
      await withCourse(id, async (tx, current) => {
        current.cancellationCleanupCompleted = true;
        await bump(tx, current);
      });
    }
  }

  async function cancelCourse(e, v) {
    requireAdmin(v);
    await withCourse(e.courseId, async (tx, c) => {
      if (c.status !== "CANCELLED") {
        c.status = "CANCELLED";
        c.cancelledAt = date(clock());
        c.cancelledBy = v.phoneNumber;
        c.cancelReason =
          typeof e.reason === "string"
            ? e.reason.slice(0, 500)
            : "ADMIN_CANCELLED";
        await bump(tx, c);
      }
    });
    await isolate(() => repairCancelled(e.courseId), "cancel repair");
    return { courseId: e.courseId, status: "CANCELLED" };
  }
  async function applyRefund(id, result, leaseToken) {
    const original = await repo.get(C.refund, id);
    if (!original) return;
    return withCourse(original.courseId, async (tx, c) => {
      const r = await tx.get(C.refund, id);
      if (!r || r.status === "SUCCESS") return;
      if (
        r.status === "FAILED" &&
        r.nextRetryAt === null &&
        result.state !== "SUCCESS"
      )
        return;
      if (leaseToken && r.leaseToken !== leaseToken) return;
      const en = await tx.get(C.enrollment, r.enrollmentId);
      const now = clock();
      r.updatedAt = date(now);
      r.leaseToken = "";
      r.leaseUntil = null;
      r.channelStatus = result.channelStatus || result.state;
      r.failureCode = result.code || "";
      if (result.state === "SUCCESS") {
        r.status = "SUCCESS";
        r.nextRetryAt = null;
        r.succeededAt = date(now);
        r.wxRefundId = result.refundId || "";
        r.failureMessage = "";
        if (en?.paymentId === r.paymentId) {
          en.status = "CANCELLED";
          en.cancelledAt = date(now);
        }
      } else if (result.state === "FAILED") {
        r.status = "FAILED";
        r.nextRetryAt = null;
        r.failureMessage = "渠道明确无法自动恢复";
        if (en?.paymentId === r.paymentId) en.status = "REFUND_FAILED";
        logger.error("refund permanently failed", {
          refundId: id,
          channelStatus: r.channelStatus,
        });
      } else {
        r.status = "PROCESSING";
        r.nextAction = result.state === "NOT_FOUND" ? "SUBMIT" : "QUERY";
        r.retryCount = (r.retryCount || 0) + 1;
        const delays = [1, 5, 15, 60];
        r.nextRetryAt = date(
          now + delays[Math.min(r.retryCount - 1, 3)] * MINUTE,
        );
        r.failureMessage = result.state === "UNKNOWN" ? "渠道结果待核实" : "";
      }
      await tx.set(C.refund, id, r);
      if (en?.paymentId === r.paymentId) {
        en.updatedAt = date(now);
        await tx.set(C.enrollment, en._id, en);
        await bump(tx, c);
      }
    });
  }
  async function runRefund(id) {
    const claimed = await repo.transaction(async (tx) => {
      const r = await tx.get(C.refund, id);
      const now = clock();
      if (
        !r ||
        r.status === "SUCCESS" ||
        r.nextRetryAt == null ||
        ms(r.nextRetryAt) > now ||
        ms(r.leaseUntil) > now
      )
        return null;
      const action = r.nextAction;
      r.leaseToken = random();
      r.leaseUntil = date(now + 2 * MINUTE);
      r.lastAttemptAt = date(now);
      r.status = "PROCESSING";
      r.nextAction = "QUERY";
      r.updatedAt = date(now);
      await tx.set(C.refund, id, r);
      return { r, action };
    });
    if (!claimed) return;
    let result;
    try {
      const p = await repo.get(C.payment, claimed.r.paymentId);
      if (!p) throw Error("PAYMENT_MISSING");
      result = await gateway[
        claimed.action === "SUBMIT" ? "submitRefund" : "queryRefund"
      ](claimed.r, p);
    } catch (err) {
      logger.error("refund transient error", {
        refundId: id,
        error: err.code || err.message,
      });
      result = { state: "UNKNOWN", code: "TEMPORARY_ERROR" };
    }
    await applyRefund(id, result, claimed.r.leaseToken);
  }
  async function refundCallback(event) {
    try {
      const no = event.outRefundNo || event.out_refund_no;
      if (!no) return { errcode: 0, errmsg: "OK" };
      const r = (await repo.scan(C.refund, { outRefundNo: no }))[0];
      if (!r) {
        logger.warn("unknown refund callback");
        return { errcode: 0, errmsg: "OK" };
      }
      if (r.status === "SUCCESS") return { errcode: 0, errmsg: "OK" };
      const p = await repo.get(C.payment, r.paymentId);
      if (!p) throw Error("PAYMENT_MISSING");
      const result = await gateway.queryRefund(r, p);
      if (result.state === "UNKNOWN" || result.state === "NOT_FOUND")
        throw Error("REFUND_QUERY_UNRESOLVED");
      await applyRefund(r._id, result);
      return { errcode: 0, errmsg: "OK" };
    } catch (err) {
      logger.error("refund callback retry", err.code || err.message);
      return { errcode: 1, errmsg: "RETRY" };
    }
  }
  async function isolate(fn, label) {
    try {
      return await fn();
    } catch (err) {
      logger.error(label, err.code || err.message);
    }
  }
  async function batch(rows, fn, concurrency = 10) {
    let index = 0;
    await Promise.all(
      Array.from({ length: Math.min(concurrency, rows.length) }, async () => {
        while (index < rows.length) {
          const row = rows[index++];
          await isolate(() => fn(row), "maintenance item");
        }
      }),
    );
  }
  async function reserve(name, id, field) {
    return repo.transaction(async (tx) => {
      const row = await tx.get(name, id);
      if (!row || (row[field] && ms(row[field]) > clock())) return false;
      // Rotate BEFORE any network call, so a terminated invocation cannot starve later work.
      row[field] = date(clock() + MINUTE);
      await tx.set(name, id, row);
      return true;
    });
  }
  async function maintenance(event, context) {
    // Distinguish a client invocation from the scheduler, not a user identity check.
    // CloudBase sends "timer"; retain "Timer" for existing test invocations.
    if (context.OPENID || !["timer", "Timer"].includes(event?.Type))
      fail("FORBIDDEN");
    const [published, confirmed, cancelled, pending, allRefunds] =
      await Promise.all([
        repo.scan(C.course, { status: "PUBLISHED" }),
        repo.scan(C.course, { status: "CONFIRMED" }),
        repo.scan(C.course, {
          status: "CANCELLED",
          cancellationCleanupCompleted: false,
        }),
        repo.scan(C.payment, { status: "PENDING" }),
        repo.scan(C.refund),
      ]);
    const due = (rows, field) =>
      rows
        .filter((r) => !r[field] || ms(r[field]) <= clock())
        .sort(
          (a, b) =>
            (ms(a[field]) || 0) - (ms(b[field]) || 0) ||
            a._id.localeCompare(b._id),
        )
        .slice(0, 50);
    const courses = due(
      [
        ...published.filter((c) => clock() >= deadlines(c).formationAt),
        ...confirmed.filter((c) => clock() >= ms(c.endAt)),
      ],
      "maintenanceAt",
    );
    // Fixed-time formation precedes all channel queries. Read actions independently
    // settle their requested course, so delayed batches cannot reopen enrollment.
    await batch(courses, async (c) => {
      if (await reserve(C.course, c._id, "maintenanceAt"))
        await settleCourse(c._id);
    });
    const paymentBatch = due(pending, "queryNextAt");
    const cancelBatch = due(cancelled, "maintenanceAt");
    const refunds = allRefunds
      .filter(
        (r) =>
          r.nextRetryAt != null &&
          ms(r.nextRetryAt) <= clock() &&
          ms(r.leaseUntil) <= clock(),
      )
      .sort(
        (a, b) =>
          ms(a.nextRetryAt) - ms(b.nextRetryAt) || a._id.localeCompare(b._id),
      )
      .slice(0, 50);
    const expiredCourseIds = [
      ...new Set(
        pending
          .filter((p) => ms(p.createdAt) + 3 * MINUTE <= clock())
          .map((p) => p.courseId),
      ),
    ].slice(0, 50);
    // Independent lanes ensure slow payment queries cannot prevent refund workers
    // from running. Each lane is capped at 50, with at most 10 network calls in flight.
    await Promise.all([
      batch(paymentBatch, async (p) => {
        if (await reserve(C.payment, p._id, "queryNextAt"))
          await confirmPayment(p._id, await gateway.queryPayment(p));
      }),
      batch(expiredCourseIds, (id) => expireCourseHolds(id)),
      batch(
        cancelBatch,
        async (c) => {
          if (await reserve(C.course, c._id, "maintenanceAt"))
            await repairCancelled(c._id);
        },
        5,
      ),
      batch(refunds, (r) => runRefund(r._id)),
    ]);
    return {
      processedCourses: courses.length + cancelBatch.length,
      processedRefunds: refunds.length,
    };
  }
  async function handle(e = {}, context = {}) {
    try {
      if (
        ![
          "context",
          "list",
          "detail",
          "publish",
          "enroll",
          "cancelEnrollment",
          "cancelCourse",
        ].includes(e.action)
      )
        fail("INVALID_ARGUMENT");
      if (
        ["detail", "enroll", "cancelEnrollment", "cancelCourse"].includes(
          e.action,
        ) &&
        (typeof e.courseId !== "string" ||
          !e.courseId ||
          e.courseId.length > 128)
      )
        fail("INVALID_ARGUMENT");
      const v = await viewer(e, context);
      const actions = {
        context: contextAction,
        list,
        detail,
        publish,
        enroll,
        cancelEnrollment,
        cancelCourse,
      };
      const data = await actions[e.action](e, v, context);
      return { success: true, data, serverTime: clock() };
    } catch (err) {
      logger.error("group course request failed", err.code || err.message);
      return {
        success: false,
        error: err instanceof BusinessError ? err.code : "INTERNAL_ERROR",
        message:
          err instanceof BusinessError
            ? err.message
            : "服务暂时不可用，请稍后重试",
        retryable: err instanceof BusinessError ? err.retryable : true,
        ...(err.details ? { details: err.details } : {}),
        serverTime: clock(),
      };
    }
  }
  return {
    handle,
    paymentCallback,
    refundCallback,
    maintenance,
    settleCourse,
    expireCourseHolds,
    confirmPayment,
    repairCancelled,
    runRefund,
    applyRefund,
  };
}
module.exports = { createService };
