// GENERATED by scripts/build-group-course.js; edit group_course/lib instead.
"use strict";
const { BusinessError } = require("./core");
// CloudBase transactions support document operations. Queries are read before the
// transaction and checked against the owning course version inside it.
function createRepository(db) {
  const get = async (root, name, id) => {
    try {
      const r = await root.collection(name).doc(id).get();
      return r.data || null;
    } catch (e) {
      if (
        /DOCUMENT_NOT_EXIST|document.*not.*exist|does not exist/i.test(
          String(e.errCode) + " " + e.message,
        )
      )
        return null;
      throw e;
    }
  };
  const wrap = (root) => ({
    get: (name, id) => get(root, name, id),
    set: async (name, id, data) => {
      const value = { ...data };
      delete value._id;
      await root.collection(name).doc(id).set({ data: value });
    },
  });
  return {
    ...wrap(db),
    // Scheduler queries must filter and limit in the database, never scan then slice.
    // Required deadlines exclude missing/null values; optional ones treat them as due.
    async findDue(name, {
      where = {}, before = {}, optionalBefore = {}, orderBy = [], limit = 50,
    }) {
      const cmd = db.command;
      const conditions = [Object.fromEntries(Object.entries(where).map(([field, value]) =>
        [field, Array.isArray(value) ? cmd.in(value) : value]))];
      for (const [field, time] of Object.entries(before)) {
        conditions.push({ [field]: cmd.exists(true) }, { [field]: cmd.neq(null) },
          { [field]: cmd.lte(time) });
      }
      for (const [field, time] of Object.entries(optionalBefore)) {
        conditions.push(cmd.or(
          { [field]: cmd.exists(false) }, { [field]: cmd.eq(null) },
          { [field]: cmd.lte(time) },
        ));
      }
      let query = db.collection(name).where(cmd.and(...conditions));
      for (const field of orderBy) query = query.orderBy(field, "asc");
      return (await query.limit(limit).get()).data;
    },
    async scan(name, where = {}) {
      const all = [];
      let last;
      for (;;) {
        const filter = last
          ? db.command.and(where, { _id: db.command.gt(last) })
          : where;
        const r = await db
          .collection(name)
          .where(filter)
          .orderBy("_id", "asc")
          .limit(100)
          .get();
        all.push(...r.data);
        if (r.data.length < 100) return all;
        last = r.data[r.data.length - 1]._id;
      }
    },
    async transaction(fn) {
      const tx = await db.startTransaction();
      try {
        const result = await fn(wrap(tx));
        await tx.commit();
        return result;
      } catch (e) {
        try {
          await tx.rollback();
        } catch (_) {}
        if (
          /TRANSACTION_CONFLICT|DATABASE_TRANSACTION_CONFLICT|write conflict|transaction.*conflict|duplicate.*key|duplicate.*index/i.test(
            String(e.errCode) + " " + e.message,
          )
        )
          throw new BusinessError(
            "RETRYABLE_CONFLICT",
            "RETRYABLE_CONFLICT",
            true,
          );
        throw e;
      }
    },
  };
}
module.exports = { createRepository };
